### ISSUE TITLE
CMake problems download libigl from gith

### ISSUE THREAD

**Issue by korzen** [Yixin-Hu/TetWild#33]
Hi Yixin-Hu,

I am getting the following error while trying to make the project:

`
  Performing update step for 'libigl-download'

  fatal: bad object 5cfc34dd1680cfe5a6e545ed9f89ae5cf2d644b7

  fatal: reference is not a tree: 5cfc34dd1680cfe5a6e545ed9f89ae5cf2d644b7

  CMake Error at E:/_TETGEN/TetWild/extern/.cache/libigl/libigl-download-prefix/tmp/libigl-download-gitupdate.cmake:147 (message):

    Failed to checkout tag: '5cfc34dd1680cfe5a6e545ed9f89ae5cf2d644b7'`

and ten 

`CMake Error at cmake/DownloadProject.cmake:179 (message):
  Build step for libigl failed: 1
Call Stack (most recent call first):
  cmake/TetWildDownloadExternal.cmake:6 (download_project)
  cmake/TetWildDownloadExternal.cmake:18 (tetwild_download_project)
  cmake/TetWildDependencies.cmake:41 (tetwild_download_libigl)
  CMakeLists.txt:76 (include)
`

Thanks for having look at this!

**Comment by Yixin-Hu** [comment]
Hi,

Thank you for reporting the problem. 

The problem has been fixed. Please pull, clean build folder and redo cmake.

**Comment by korzen** [comment]
Thanks!
