### ISSUE TITLE
Question: How far away is a version without CGAL code?

### ISSUE THREAD

**Issue by noname-2** [Yixin-Hu/TetWild#34]
How far away is a version without CGAL code?

**Comment by Yixin-Hu** [comment]
Hi,

I think it's postponed to next year. I have no time to do the modification and testing work by myself this year. If someone else is involved, it could be faster.

**Comment by Yixin-Hu** [comment]
Hi,

It's not scheduled and it's not on my task list now. Could you tell me the reason why you don't want CGAL? I may have alternate suggestions.

**Comment by pierre-leon** [comment]
Hi @Yixin-Hu, 
TetWild is great and I'm always amazed by how robust it is even with bad inputs.

We're interested in using TetWild in a commercial application (hence the problem with CGAL).
1. If you do have alternate suggestions, that would be great.
2. Alternatively, we'll be looking to get a commercial license from CGAL to be able to implement TetWild, what module(s) of CGAL are required?
Thanks! 🎅

**Comment by Yixin-Hu** [comment]
Hi, 

we CGAL-free version released recently (https://github.com/wildmeshing/fTetWild). You can try it out.

Thanks,
Yixin

**Comment by pierre-leon** [comment]
Thanks!

**Comment by jdumas** [comment]
I think this issue can be closed then?
