### ISSUE TITLE
Flag to disable winding numbers

### ISSUE THREAD

**Issue by mlivesu** [Yixin-Hu/TetWild#37]
Hi, 
I'd like to use TetWild to tetrahedralize a non orientable triangle mesh containing both outer surface and inner structures. Tet filtering based on winding numbers is currently destroying all my results, so I'd like to disable such filtering, and do it by myself in post processing. Is it possible to expose a flag to disable winding numbers and output a tetmesh of the whole outer hull? 
Thank you!

**Comment by jdumas** [comment]
Hi Marco. In/Out filtering happens [here](https://github.com/Yixin-Hu/TetWild/blob/master/src/tetwild/InoutFiltering.cpp#L45). I believe you can hack around to disable this filtering, although it'd make sense to expose such a flag at some point.

**Comment by Yixin-Hu** [comment]
Hi,

I exposed the flag `--save-mid-result`. Please use `--save-mid-result 2`.

**Comment by mlivesu** [comment]
Thank you very much Yixin and Jeremie!
