### ISSUE TITLE
Segementation Fault without calling GEO::initialize();

### ISSUE THREAD

**Issue by zero-impact** [Yixin-Hu/TetWild#38]
I am using TetWild as a submodule in my project so that I can call `tetwild::tetrahedralization()` directly.

However, I have found that you must call `GEO::initialize();` included from `#include <geogram/basic/common.h>` before calling tetwild, otherwise it will result in an immediate segmentation fault.

It might be helpful to not this in the README, or else call it automatically.

I'm building on OSX 10.14.

**Comment by Yixin-Hu** [comment]
Hi,

Thank you for reporting this problem. Yes, it's true that `GEO::initialize()` has to be called before using geogram functions. I've added the initialization into `tetwild::tetrahedralization()`.

**Comment by zero-impact** [comment]
Wonderful!
