### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by fdelpin** [Yixin-Hu/TetWild#42]
Hi,
I am trying to reproduce the case "figures_data/fig4" using the epsilon value 100 for the coarser mesh. I see that TetWild does all the pre-processing stage and then it gets stuck in "Delaunay tetrahedralizing" and the memory usage increases to about 25 GB. It runs for about an hour before I kill it. I use the same command line described in the file "run.sh". Is this behavior normal? Should I wait longer? 
I am looking forward to testing TetWild in other models.
Thanks,
Facundo.

**Comment by Yixin-Hu** [comment]
Hi,

Thank you for reporting it. That script is for the original old code. We changed the way to input parameters. 
Old: real_epsilon = diag_of_bbox / input_epsilon
New: real_epsilon = diag_of_bbox * input_epsilon
For example, if you want to use epsilon equal to the 0.1% of diagonal of the bbox, you should use `--epsilon 0.01` now. Please refer to our documentation for more details.

Sorry about that. I will fix it asap.

**Comment by fdelpin** [comment]
Hi Yixin,

thanks for your quick answer. It is working fine now. 

Regards,
Facundo.
