### ISSUE TITLE
Settings for libigl example [truck.obj]

### ISSUE THREAD

**Issue by gbivins** [Yixin-Hu/TetWild#46]
TetWild is really great! I've successfully run it on some other models but I can't quite figure out good settings for one of the examples out of libigl.
For this input
![truck interesting](https://user-images.githubusercontent.com/1735516/53784479-0e49fa80-3edb-11e9-841f-062a8ec41663.png)

I'm getting this output with the default settings:
![tetwild truck ooops](https://user-images.githubusercontent.com/1735516/53784520-2ae63280-3edb-11e9-8aef-7d36f8caf2ab.png)

I made a couple runs at decreasing epsilon but it only gave me more tets with the same general output as above but taking more time.
Any recommendations for epsilon and/or edge length parameters?
Source model is from libigl [truck.obj](https://github.com/libigl/libigl-tutorial-data/blob/master/truck.obj)

**Comment by Yixin-Hu** [comment]
Hi,

This model has inverted faces. TetWild tracks input faces with the orientation, which is used in the final step winding number. 
![image](https://user-images.githubusercontent.com/25575671/53816266-47ad5500-3f31-11e9-8d7f-160a2ef54046.png)

Please refer to the first few lines in https://github.com/Yixin-Hu/TetWild/blob/master/README.md for the reason how orientation matters.

**Comment by gbivins** [comment]
Got it. Makes sense. Great work with TetWild btw 💯
