### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by yig** [Yixin-Hu/TetWild#48]
I created a Dockerfile for TetWild. So if you have Docker installed, you can just do:

    docker pull ygingold/tetwild

and then to run it:

    docker run --rm -v "$(pwd)":/data ygingold/tetwild [TetWild arguments]

For example:

    docker run --rm -v "$(pwd)":/data ygingold/tetwild --input input.stl --ideal-edge-length 200

I think you can add this to the README.

**Comment by yig** [comment]
The Dockerfile itself is really short:

```
# Use an official Python runtime as a parent image
FROM ubuntu

# Install any needed packages specified in requirements.txt
RUN apt-get update && apt-get install -y git cmake g++ libcgal-dev

# Set the working directory to /app
WORKDIR /app

# Download and compile TetWild
RUN git clone https://github.com/Yixin-Hu/TetWild --recursive
WORKDIR /app/TetWild/build
RUN cmake .. && make

WORKDIR /data

ENTRYPOINT ["/app/TetWild/build/TetWild"]

## Create TetWild image with:
# docker build -t tetwild .
## Run TetWild with:
# docker run --rm -v "$(pwd)":/data tetwild [TetWild arguments]
```

**Comment by Yixin-Hu** [comment]
Thank you for providing the scripts!
