### ISSUE TITLE
tetWild on for surface

### ISSUE THREAD

**Issue by lizhen22** [Yixin-Hu/TetWild#50]
Hi, all,
I use openscad to generate geometry using stl file. But sometime the triagulation of CGAL is not perfect. Other cad tools can not handle it cause of some surface errors. I used tetWild to get a better surface mesh, however the process crushed due to memory problem for a very large case. My question is, Could I run tetWild only to create a high-quality surface without meshing the whole volume?

thanks a lot!

best regards

**Comment by Yixin-Hu** [comment]
Hi,

There's no way to use TetWild to generate a clean surface mesh without generating tetmesh.

TetWild is a tetrahedral meshing algorithm. Surface cleanup is just its by-product.
