### ISSUE TITLE
These surface mesh files are empty in 10k surface meshes

### ISSUE THREAD

**Issue by hoosha** [Yixin-Hu/TetWild#51]
The length of these files in 10k surface meshes are 2 bytes!
100331_sf.obj
1004825_sf.obj
101213_sf.obj
101214_sf.obj
1017018_sf.obj
103085_sf.obj
103212_sf.obj
103519_sf.obj
103537_sf.obj
115423_sf.obj
117950_sf.obj
1230687_sf.obj
124708_sf.obj
128344_sf.obj
128911_sf.obj
131438_sf.obj
132349_sf.obj
133582_sf.obj
135465_sf.obj
136385_sf.obj
1389867_sf.obj
1505134_sf.obj
1505135_sf.obj
178340_sf.obj
188019_sf.obj
214481_sf.obj
264708_sf.obj
366724_sf.obj
38096_sf.obj
39585_sf.obj
39946_sf.obj
40010_sf.obj
40011_sf.obj
40607_sf.obj
40888_sf.obj
41909_sf.obj
42372_sf.obj
42633_sf.obj
42840_sf.obj
42841_sf.obj
43190_sf.obj
43978_sf.obj
45132_sf.obj
46244_sf.obj
46649_sf.obj
47877_sf.obj
49741_sf.obj
49742_sf.obj
49743_sf.obj
49794_sf.obj
49867_sf.obj
49900_sf.obj
49901_sf.obj
49902_sf.obj
50305_sf.obj
50306_sf.obj
50307_sf.obj
50309_sf.obj
51328_sf.obj
51354_sf.obj
51358_sf.obj
526843_sf.obj
55557_sf.obj
55574_sf.obj
56527_sf.obj
57896_sf.obj
57897_sf.obj
63788_sf.obj
66773_sf.obj
68247_sf.obj
68256_sf.obj
68731_sf.obj
70374_sf.obj
71531_sf.obj
71692_sf.obj
71988_sf.obj
72015_sf.obj
72094_sf.obj
723899_sf.obj
73081_sf.obj
73083_sf.obj
73336_sf.obj
75851_sf.obj
76540_sf.obj
76541_sf.obj
78735_sf.obj
78970_sf.obj
80175_sf.obj
80177_sf.obj
80178_sf.obj
80609_sf.obj
80610_sf.obj
80751_sf.obj
80761_sf.obj
82541_sf.obj
83647_sf.obj
83719_sf.obj
888457_sf.obj
901212_sf.obj
901213_sf.obj
901214_sf.obj
92065_sf.obj
93716_sf.obj
95404_sf.obj
95409_sf.obj
95410_sf.obj
95411_sf.obj
95412_sf.obj
95413_sf.obj
95414_sf.obj
95416_sf.obj
95417_sf.obj
95418_sf.obj
95419_sf.obj
95420_sf.obj
95421_sf.obj
95422_sf.obj
95423_sf.obj
95425_sf.obj
95426_sf.obj
95427_sf.obj
95428_sf.obj
95429_sf.obj
95430_sf.obj
95431_sf.obj
95432_sf.obj
95433_sf.obj
95434_sf.obj
95435_sf.obj
95436_sf.obj
95783_sf.obj
96574_sf.obj
988105_sf.obj
996806_sf.obj
99943_sf.obj

**Comment by Yixin-Hu** [comment]
Hi, these input are with all faces inverted, which makes the outside regarded as "inside". So the output is empty before. We added another step to deal with this problem, that is we do outside filtering with inverted input orientation inverted.

**Please try tetwild on these models again. It should work well.**

**Comment by hoosha** [comment]
@Yixin-Hu Thank you.
Would you be able to kindly update the surface meshes in the google drive so I can just download the pre-generated meshes? :)

**Comment by Yixin-Hu** [comment]
I don't have them right now. I will regenerate the results for those input.

**Comment by hoosha** [comment]
Thank you!

**Comment by hoosha** [comment]
Are they updated now? @Yixin-Hu

**Comment by Yixin-Hu** [comment]
Hi, they haven't updated yet. I'm occupied with something else these days and I'll update them when I have time. I would suggest you generate them by yourself using tetwild instead of waiting for my update if it's urgent.
