### ISSUE TITLE
Use of GeoGram and CGAL

### ISSUE THREAD

**Issue by 461353349** [Yixin-Hu/TetWild#52]
I have some questions:
1) We use CGAL not GeoGram for tet mesh generation, Is it just because of rational float?
2) We use GeoGram just for quickly computing facet intersection and locating the nearest facet, Is it right?
3) I notice quad mesh and hex mesh generation in your PPT, Could you tell me what library or tools to generate them?
Thanks a lot.

**Comment by Yixin-Hu** [comment]
Hi,

I assume the "We" in 1 and 2 refers our method TetWild.

1. We can also use geogram for background delaunay mesh generation. 
2. Yes.
3. We use https://github.com/gaoxifeng/robust_hex_dominant_meshing

**Comment by 461353349** [comment]
Yes, It refers to TetWild :)
That is to say, Delaunay Algorith is closed only if rational is enough. So TetWild use CGAL or GeoGram  for tet generation has no difference. Does GeoGram support rational if using GeoGram for tet mesh generation? Or Only Splitting and orientation need rational?
If TetWild directly use gmp for rational data type, TetWild Maybe not depend on CGAL library. Is it right?

**Comment by Yixin-Hu** [comment]
Delaunay Algorithm can be down in floating points. I don't know if geogram supports rationals. We are not using geogram with rationals. GMP rational is slower than cgal rational. But yes, we can use gmp only. For example, our 2D implementation only depends on gmp.

**Comment by 461353349** [comment]
Thanks very much!!!
