### ISSUE TITLE
geogram-download

### ISSUE THREAD

**Issue by 24332006** [Yixin-Hu/TetWild#54]
error: could not find git for clone of geogram-download！
Can you help me with it? Thank you！

**Comment by 24332006** [comment]
I also checked the link is no problem, but there will be a download error, I am connected to the China network.

> 你好
> 
> git地址正确，我刚才再次检查了一下。很奇怪，它对您不利。可能是互联网问题。您连接到哪个国家的互联网？

**Comment by Yixin-Hu** [comment]
Please try using VPN. Maybe try connecting to US.

**Comment by 24332006** [comment]
> 请尝试使用VPN。也许尝试连接到美国。

Ok, let me try it, thank you!

**Comment by 24332006** [comment]
> 请尝试使用VPN。也许尝试连接到美国。

I have switched to the US network, unfortunately, it still failed.

**Comment by Yixin-Hu** [comment]
Could you post the whole cmake output?

**Comment by 24332006** [comment]
> 您可以发布整个cmake输出吗？

No build type selected, default to Release
Downloading/updating geogram
CMake Error at D:/CMake/cmake-3.16.0-rc1-win64-x64/share/cmake-3.16/Modules/ExternalProject.cmake:2421 (message):

  error: could not find git for clone of geogram-download
Call Stack (most recent call first):
  D:/CMake/cmake-3.16.0-rc1-win64-x64/share/cmake-3.16/Modules/ExternalProject.cmake:3236 (_ep_add_download_command)
  CMakeLists.txt:9 (ExternalProject_Add)



-- Configuring incomplete, errors occurred!

See also "E:/tetwild/TetWild-master/extern/.cache/geogram/CMakeFiles/CMakeOutput.log".

CMake Error at cmake/DownloadProject.cmake:171 (message):
  CMake step for geogram failed: 1
Call Stack (most recent call first):
  cmake/TetWildDownloadExternal.cmake:6 (download_project)
  cmake/TetWildDownloadExternal.cmake:26 (tetwild_download_project)
  cmake/TetWildDependencies.cmake:14 (tetwild_download_geogram)
  CMakeLists.txt:79 (include)


Configuring incomplete, errors occurred!
See also "E:/tetwild/TetWild/CMakeFiles/CMakeOutput.log".

**Comment by 24332006** [comment]
> 您可以发布整个cmake输出吗？

No build type selected, default to Release
Downloading/updating geogram
CMake Error at D:/CMake/cmake-3.16.0-rc1-win64-x64/share/cmake-3.16/Modules/ExternalProject.cmake:2421 (message):

  error: could not find git for clone of geogram-download
Call Stack (most recent call first):
  D:/CMake/cmake-3.16.0-rc1-win64-x64/share/cmake-3.16/Modules/ExternalProject.cmake:3236 (_ep_add_download_command)
  CMakeLists.txt:9 (ExternalProject_Add)



-- Configuring incomplete, errors occurred!

See also "E:/tetwild/TetWild-master/extern/.cache/geogram/CMakeFiles/CMakeOutput.log".

CMake Error at cmake/DownloadProject.cmake:171 (message):
  CMake step for geogram failed: 1
Call Stack (most recent call first):
  cmake/TetWildDownloadExternal.cmake:6 (download_project)
  cmake/TetWildDownloadExternal.cmake:26 (tetwild_download_project)
  cmake/TetWildDependencies.cmake:14 (tetwild_download_geogram)
  CMakeLists.txt:79 (include)


Configuring incomplete, errors occurred!
See also "E:/tetwild/TetWild/CMakeFiles/CMakeOutput.log".

**Comment by Yixin-Hu** [comment]
Could you try manually cloning geogram repository (https://github.com/alicevision/geogram) into `TetWild/extern/` folder? If cmake works correctly, it will download 5 libraries into `extern` folder.
![image](https://user-images.githubusercontent.com/25575671/67731229-dfcee180-f9cd-11e9-885d-1c8d2414705a.png)

**Comment by jdumas** [comment]
The error message says clearly what's wrong: you need to install git. Do not forget to add it to your PATH so CMake can find it.

**Comment by Yixin-Hu** [comment]
Ah yes, Jeremie is correct.

**Comment by 24332006** [comment]
The above questions are solved, thank you very much. But it will have a new problem.

Creating target: igl::core (igl)
CMake Error at cmake/DownloadProject.cmake:179 (message):
  Build step for cgal failed: 1
Call Stack (most recent call first):
  extern/libigl/cmake/LibiglDownloadExternal.cmake:14 (download_project)
  extern/libigl/cmake/LibiglDownloadExternal.cmake:28 (igl_download_project)
  extern/libigl/cmake/libigl.cmake:193 (igl_download_cgal)
  cmake/FindLIBIGL.cmake:33 (include)
  cmake/TetWildDependencies.cmake:42 (find_package)
  CMakeLists.txt:79 (include)
