### ISSUE TITLE
Feature request - Curve Constraints

### ISSUE THREAD

**Issue by pierre-leon** [Yixin-Hu/TetWild#58]
Is there a way to constrain the tetrahedrons to be generated so they comply with curves on the surface mesh? (line segments / edge list from the original surface mesh).

**Comment by pierre-leon** [comment]
One approach we had in mind is to post process -  split tetrahedron where there's an edge. But this will create a large variance in tet sizes.

**Comment by Yixin-Hu** [comment]
Hi,

TetWild does not support feature preservation for now.

Thanks,
Yixin
