### ISSUE TITLE
Can you please update your CMakeLists.txt for Mac OS  X?

### ISSUE THREAD

**Issue by nyotis** [Yixin-Hu/TetWild#6]
Paths need to be tweaked -- boost, cgal, sort of automatically installed via homebrew.

Is igl also a dependency?
Matlab as well!?

**Comment by Yixin-Hu** [comment]
Hi, 

no need to tweak paths, it should find cgal automatically. 

We use libigl and geogram as submodules. igl is the namespace of libigl. We don't use matlab.

**Comment by nyotis** [comment]
Hi,

it should but it doesn't.. I will try again -- thanks for the rest of the info

**Comment by Yixin-Hu** [comment]
You are welcome!

**Comment by nyotis** [comment]
<img width="1676" alt="screen shot 2018-06-16 at 13 59 52" src="https://user-images.githubusercontent.com/658719/41498425-b1334486-716d-11e8-958c-2c421f0e662c.png">

Hmm... my $PATH includes the homebrew I use for CGAL and Boost -- apparently, this is not enough. Can anyone confirm building the source on OS X? I do not want to edit CMakeLists.txt unless if there is no alternative

Cheers!
