### ISSUE TITLE
Input surface identification from output mesh

### ISSUE THREAD

**Issue by Rgtemze** [Yixin-Hu/TetWild#60]
Hi,
Before all, thanks for developing this tetrahedralization tool. 

Our issue is the following,
since after tetrahedralization (without filtering) input stays inside the bounding box, we need to know which faces in the output mesh belong to surface. We used is_on_surface variable of TetVertex class for that purpose but it occurred to us that some of the surface faces were not covered. Yet, the figure from your paper suggests that you could identify faces corresponding to the surface.

![image](https://user-images.githubusercontent.com/8372277/73489561-d6358b00-43bb-11ea-91ee-7d7c7345f38b.png)

Sincerely

**Comment by Yixin-Hu** [comment]
Hi,

The correct way to extract the embedded surface is to output final tetmeshes with and without winding number. The surface of the tetmesh with winding number is the embedded surface of the other one.

You can output the meshes before and after this line which is for applying winding number (in/out filtering):
https://github.com/Yixin-Hu/TetWild/blob/master/src/tetwild/InoutFiltering.cpp#L80
(According to your message, I assume that you kind of know my code.)

Hope this helps
