### ISSUE TITLE
Multi-Material Meshing

### ISSUE THREAD

**Issue by jonathanhestroffer** [Yixin-Hu/TetWild#61]
Hi,

I have a "part" which is multi-material. I have an .STL file for every material surface mesh and I would like to perform volume meshing and output the tetmesh for each material. I attached an image of an example part and as you can see each unique material is colored.

![Multimaterial](https://user-images.githubusercontent.com/55960462/75213896-80e16500-5740-11ea-86f6-b39cfc34ed88.PNG)

Using a different program, I can get a volume mesh in the form I need (tets assigned to a particular material Id), but the mesh quality isn't great. Do you think I can use TetWild for this?

![Multimaterial2](https://user-images.githubusercontent.com/55960462/75214252-c4889e80-5741-11ea-95bf-2c26f1e6202d.PNG)

Best :)
Jonathan

**Comment by Yixin-Hu** [comment]
Hi Jonathan,

Yes,  you can try tetwild on it. After you get the tetmesh, you can write a function to postprocess the mesh taking a 3d point (the centroid of a tet) as input and returning the material it belongs to. 

Hope this helps,
Yixin

**Comment by jonathanhestroffer** [comment]
After some research I came across Generalized Winding Number.

What do you think?

Best,
Jonathan

**Comment by Yixin-Hu** [comment]
You can use winding number, but during this step (not meshing step) you need to make sure the faces of each component has same orientation (the face normals point outside of the component).

**Comment by jonathanhestroffer** [comment]
Thank you Yixin!

**Comment by rossisimone** [comment]
I am also interested in creating a multimaterial mesh. 
How can we do that with TetWild?

I have 3 complex "concentrical" tubes defined as STL files. 
I would like to define a volumetric mesh of the whole thing such that the final tet mesh "conforms" to the provided surface layers. 
I was able to create a separate tet mesh for each of the STLs, but I'm not sure how to use the multimaterial functionalities. 

I can easily postprocess it to assign the materials in a second step. 

Thanks,
Simone

**Comment by Yixin-Hu** [comment]
TetWild preserves all faces both inside and outside. You can combine your STLs into one and run tetwild on it. After you get the tetmesh, do the postprocessing I mentioned above.
