### ISSUE TITLE
Quit at Delaunay Tetrahedralizing step

### ISSUE THREAD

**Issue by jonathanhestroffer** [Yixin-Hu/TetWild#62]
Hi Yixin,

I am using TetWild on a relatively large surface mesh (500,000 vertices)

The program stops at "Delaunay Tetrahedralizing" step. How should I go about solving this? Is this an issue with small "sliver" mesh?

Best,
Jonathan
![Capture](https://user-images.githubusercontent.com/55960462/76152556-a3934800-6075-11ea-89f2-01cdfe105ca4.PNG)

**Comment by Yixin-Hu** [comment]
Hi Jonathan, this should not happen. "Sliver" input should not matter. Could you share the input?

**Comment by jonathanhestroffer** [comment]
Hi Yixin,

I believe the message doesn't relate to sliver input. I did some more work
and realized that my manner of trying to get finer mesh is causing the
problem.

Attached is the input surface mesh I am using , "whole.stl" , and below are
some of the commands (through Docker) I have been trying to get a finer
mesh. I have only been changing ideal edge length and at some value of "-l"
the program terminates, but with no error. I was hoping you might know why
this is happening. I would also appreciate any advice on how to refine the
mesh further.

Best,
Jonathan

*Default*
[image: image.png]
[image: image.png]

*L = 0.01*
[image: image.png]
[image: image.png]

*L=0.005* - Fail
[image: image.png]
[image: image.png]

**Comment by Yixin-Hu** [comment]
I couldn't find the file in my mail box. Could you directly send it to me via email (yixin.hu@nyu.edu)? I tried `-l 0.005` on a random model, it works fine. So I think I will need the model to debug.

Thanks

**Comment by Yixin-Hu** [comment]
Hi, I tested your model on MacOS and Linux, the code works without unexpected termination. The model you sent only contains 2558 faces. Is it the input that caused the problem?

**Comment by jonathanhestroffer** [comment]
Hi Yixin,

I tested this again and I get the same termination.

I forgot to mention I am using Docker, is this an issue related to using
containers? Possibly memory?

**Comment by Yixin-Hu** [comment]
This is possible. Please check the memory usage and limits by `docker stats`.

**Comment by jonathanhestroffer** [comment]
Hi Yixin,

I adjusted the memory limits and it now works.

Thank you very much!

**Comment by Yixin-Hu** [comment]
great
