### ISSUE TITLE
Model problems

### ISSUE THREAD

**Issue by 24332006** [Yixin-Hu/TetWild#64]
Hello, can tetwild handle non manifold, repeating point and model with boundary? thank you!

**Comment by Yixin-Hu** [comment]
Yes. The surface should be correct oriented so that winding number (the final step of tetwild) can extract the volume correctly.

**Comment by 24332006** [comment]
> Yes. The surface should be correct oriented so that winding number (the final step of tetwild) can extract the volume correctly.

Being able to handle these models, I think tetwild is great! Thank you.
