### ISSUE TITLE
Abnormal program termination: received signal 11 (Segmentation fault)

### ISSUE THREAD

**Issue by jonathanhestroffer** [Yixin-Hu/TetWild#67]
Hi Yixin,

I am using TetWild built in a linux container. Inside the "/app/TetWild/build" directory I run, 

./TetWild --help 

and everything looks good. Inside this directory I have also put a test .stl file. I am trying to run the program with,

./TetWild --input test.stl

and I get this error... "Abnormal program termination: received signal 11 (Segmentation fault)". Do I need to store the .stl in a different directory for the program to function?

Thanks,
Jonathan

**Comment by Yixin-Hu** [comment]
Hi, 

I think this should work. `--input` takes relative path and absolute path. Could you share your .stl file?

**Comment by jonathanhestroffer** [comment]
Hi Yixin,

I have solved the problem. Thank you!

Best,
Jonathan

**Comment by Yixin-Hu** [comment]
Ok, great!

**Comment by AadityaKhetan** [comment]
Hi @jonathanhestroffer ,
Could you please tell us how did you solve this issue.

**Comment by jonathanhestroffer** [comment]
Hi,

I don't recall this problem exactly, but most likely the input surface mesh
was defective.
