### ISSUE TITLE
Compilation issue on Ubuntu 18.04

### ISSUE THREAD

**Issue by steve-fitzgerald** [Yixin-Hu/TetWild#7]
I am trying to compile TetWild on Ubuntu 18.04 and get the following errors
/home/sfitz/Tools/TetWild/LocalOperations.cpp: In member function ‘void LocalOperations::check()’:
/home/sfitz/Tools/TetWild/LocalOperations.cpp:310:66: error: ‘const class __gmp_expr<__mpq_struct [1], __mpq_struct [1]>’ has no member named ‘numerator’; did you mean ‘operator=’?
             int tmp_n_size = CGAL::exact(tet_vertices[i].pos[j]).numerator().bit_size();
                                                                  ^~~~~~~~~
/home/sfitz/Tools/TetWild/LocalOperations.cpp:311:66: error: ‘const class __gmp_expr<__mpq_struct [1], __mpq_struct [1]>’ has no member named ‘denominator’
             int tmp_d_size = CGAL::exact(tet_vertices[i].pos[j]).denominator().bit_size();
                                                                  ^~~~~~~~~~~
CMakeFiles/lib_tetwild.dir/build.make:206: recipe for target 'CMakeFiles/lib_tetwild.dir/LocalOperations.cpp.o' failed
make[2]: *** [CMakeFiles/lib_tetwild.dir/LocalOperations.cpp.o] Error 1

Ubuntu 18.04 uses gmp 2:6.1.2+dfsg-2 source package, and
Ubuntu 16.04 uses gmp 2:6.1.0+dfsg-2 source package
Ubuntu 18.04 uses cgal 4.11-2build1 source package

Downloaded and installed CGAL 4.12 with gmp support and received the same errors
Compiled and installed CGAL 4.12 with gmp deselected and received the same errors because CGAL cmake still finds the package.

Downloaded latest gmp from GNU (had to install m4 package) compile and install
Downloaded latest mpfr from GNU, compile and install

Recompile CGAL 4.12 with locally compiled versions of gmp and mpfr, got the same errors
My next move is to bring down gmp 6.1.0 and see if that fixes the issue

**Comment by Yixin-Hu** [comment]
Hi,

please try commenting out line 310-315 in file `LocalOperations.cpp` (those lines are not necessary) and see if it can go through.

**Comment by steve-fitzgerald** [comment]
Thanks for the simple option. That fixes the compilation issue. I'll run some examples and let you know how it goes.
