### ISSUE TITLE
Remove dependency on CGAL

### ISSUE THREAD

**Issue by hph73** [Yixin-Hu/TetWild#70]
Although TetWild is released under MPL but its dependency CGAL is licensed under GPL, which makes it prohibitive for commercial use. Is removing GPL dependencies on the path forward?

**Comment by Yixin-Hu** [comment]
Hi, 

We have fTetWild, a fast version of TetWild without CGAL dependency, released recently: https://github.com/wildmeshing/fTetWild. 

fTetWild works similarly to TetWild but uses a different algorithm. For more details, please check our paper: https://github.com/wildmeshing/fTetWild#important-tips

**Comment by hph73** [comment]
Hi Yixin,

Thanks for your prompt response. The fTetWild library is definitely helpful and I have successfully got it compiled on Centos. I will take a close look at your paper. Thanks for your excellent work.

Hao
