### ISSUE TITLE
How to make tetrahedron coarse

### ISSUE THREAD

**Issue by JerryYan97** [Yixin-Hu/TetWild#72]
Hello!

I am new to this tool and it looks cool. I am wondering how to make tetrahedron more coarsen by adjusting parameters.
E.g. I am trying to use TetWild to tetrahedralize a 3D bar and I am now increasing the -l/-a number, but it looks like the number of the final tetrahedron would stay at some level (~2000 tets) and I want to make them to be less than a thousand.

Can I further decrease the number of tets? Are there other parameters that I should adjust?

Thank you!

**Comment by Yixin-Hu** [comment]
Hi,

`-l` controls the max edge length. To coarsen the output mesh one step further, you may try fTetWild (https://github.com/wildmeshing/fTetWild) with the flag `--coarsen` (I haven't added this flag in TetWild). TetWild and fTetWild output very similar results but use different algorithms. fTetWild is more efficient.

**Comment by JerryYan97** [comment]
Cool! 

I try it. Sorry that I didn't notice your new research :)

Thank you very much!
