### ISSUE TITLE
Compilation on M1 Mac

### ISSUE THREAD

**Issue by janba** [Yixin-Hu/TetWild#76]
Hi

Thanks for TetWild!  I would like to try it, and I am trying to compile, and getting stuck with the prerequisites. Specifically, it seems that libIGL which needs CGAL won't compile because the version of Boost is insufficient. Now, both Boost and CGAL were installed with Mac Ports, but the CGAL5 installation appears to be ignored and it does not like the installed version of Boost. I could try the Docker version, but it seems to require an Intel Mac. I attach the pertinent output from `cmake ..`. I have tried `-DTETWILD_WITH_HUNTER=ON` but also without luck:  I get compilation errors. Perhaps these can be resolved, but I would like to hear if you have any thoughts before going further?

Thanks!

```
Cloning into 'cgal'...
HEAD is now at f7c3c8212b The announcement draft
BOOST_ROOT: 
-- Using header-only CGAL
-- Targetting Unix Makefiles
-- Using /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ compiler.
-- DARWIN_VERSION=20
-- Mac Leopard detected
-- Found GMP: /opt/local/lib/libgmp.dylib  
-- Found MPFR: /opt/local/lib/libmpfr.dylib  
-- __cplusplus is 199711
CMake Error at /opt/local/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find Boost (missing: thread system) (found suitable version
  "1.71.0", minimum required is "1.48")
Call Stack (most recent call first):
  /opt/local/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  /opt/local/share/cmake-3.19/Modules/FindBoost.cmake:2193 (find_package_handle_standard_args)
  extern/libigl/external/cgal/Installation/cmake/modules/CGAL_SetupBoost.cmake:48 (find_package)
  extern/libigl/external/cgal/Installation/cmake/modules/CGAL_SetupCGALDependencies.cmake:52 (include)
  extern/libigl/external/cgal/Installation/lib/cmake/CGAL/CGALConfig.cmake:106 (include)
  extern/libigl/external/cgal/CGALConfig.cmake:6 (include)
  extern/libigl/cmake/libigl.cmake:233 (find_package)
  cmake/FindLIBIGL.cmake:33 (include)
  cmake/TetWildDependencies.cmake:42 (find_package)
  CMakeLists.txt:79 (include)
```

**Comment by danielepanozzo** [comment]
Hi Andreas,

neither libigl or tetwild have been ported yet to macosx arm. We are planning to do it at some point but not currently as we do not have an M1 mac yet. 

In the meantime, if you compile it on windows, mac (intel), or Linux it should work out of the box! If you manage to fix both libigl and tetwild to compile on M1, could you please send us a PR with the changes? We would be happy to integrate it.

Daniele

**Comment by janba** [comment]
HI Daniele,

Thanks! I might just check it on my Intel laptop instead :) 

However, it seems that libigl is the problem. Compiling with CGAL I get the problem above (`Could NOT find Boost (missing: thread system)`). Compiling without CGAL, the vector math instructions used in fast winding number computation is the issue. I switched off embree in CMakeLists.txt but this is not sufficient.

Best 
Andreas
