### ISSUE TITLE
论文《Tetrahedral Meshing in the Wild》和对应程序学习请教

### ISSUE THREAD

**Issue by 1044574240** [Yixin-Hu/TetWild#77]
胡学姐好，我想请较下想看懂这篇算法的程序和理解内容，需要补充学些那些方面的知识？(目前在学习b站c++课程和计算几何的部分知识，同时一字一字试着翻译这篇《Tetrahedral Meshing in the Wild》论文)
感谢赐教！
来自：郑大研一网格算法方向学生阿成

**Comment by Yixin-Hu** [comment]
你好，如果你是刚开始接触四面体网格生成，你可以先去了解一下应用最广泛的Delaunay Tetrahedralization算法。就TetWild而言，可以学习一下BSP subdivision, AABB tree, local operations in mesh improvement (edge splitting, edge collapsing, edge swapping, vertex smoothing), CGAL或GMP库中的arbitrary-precision的数据类型（rational number）。希望对你有帮助。

**Comment by 1044574240** [comment]
很感谢您的回复，我这就把您提到的内容加入学习计划。我目前在mac虚拟机，linux虚拟机上，都对tetwild成功复现了示例中的结果，再次感谢学姐的赐教。
