### ISSUE TITLE
Sizing Field

### ISSUE THREAD

**Issue by jonathanhestroffer** [Yixin-Hu/TetWild#78]
Hi Yixin,

I would like to generate mesh with small elements close to input surface and larger elements farther away. I see there is an option for a sizing field in a background .msh file, but I am unsure how to create this. 

How can I create this sizing field?

Best,
Jonathan

**Comment by Yixin-Hu** [comment]
Hi Jonathan,

You can create a uniform background tetmesh for a box a bit larger than the model and assign the sizing field for the background mesh (you can use `#include <pymesh/MshSaver.h>` to write a mesh with fields) according to the distance to the input surface.

Hope this helps,
Yixin
