### ISSUE TITLE
Uses two versions of  mesh_AABB header and source file each, at the same time (!) - please rename at least and clarify

### ISSUE THREAD

**Issue by Mathias-Fuchs** [Yixin-Hu/TetWild#88]
```
$ find -name mesh_AABB.h
./extern/geogram/src/lib/geogram/mesh/mesh_AABB.h
./src/tetwild/geogram/mesh_AABB.h
$ find -name mesh_AABB.cpp
./extern/geogram/src/lib/geogram/mesh/mesh_AABB.cpp
./src/tetwild/geogram/mesh_AABB.cpp
```
Both mesh_AABB.h seem to be _almost_ but not exactly the same. I am very sorry to be so direct, but this is quite a whacky way to write software and causes worries for everyone who wants to work with the code.

**Comment by Yixin-Hu** [comment]
Hi,

`./extern/geogram/src/lib/geogram/mesh/mesh_AABB.h/cpp` is the code inside the dependent library Geogram. `./src/tetwild/geogram/mesh_AABB.h/cpp` is the code we reimplemented recycling the most part of `./extern/geogram/src/lib/geogram/mesh/mesh_AABB.h/cpp` with small (but important) changes.
