### ISSUE TITLE
multi-material meshing with shared faces 

### ISSUE THREAD

**Issue by iszihan** [Yixin-Hu/TetWild#89]
Hello, I have a multi-material meshing situation in which I have two meshes with adjacent faces. I'm wondering if TetWild support meshing both meshes/materials while preserving the touching faces with the same triangulation? If so, how do I access such support? Thank you!

**Comment by vikorj** [comment]
Seems like this has been done here?
https://doi.org/10.1016/j.cmpb.2022.107140

**Comment by Yixin-Hu** [comment]
Hi,

Yes, TetWild tracks and preserves input surface mesh both inside (the adjacent faces you mentioned) and outside. You can try to use this function to extract the tracked surface: https://github.com/Yixin-Hu/TetWild/blob/master/src/tetwild/MeshRefinement.h#L92C10-L92C10
