### ISSUE TITLE
Mac OS X build issue

### ISSUE THREAD

**Issue by nyotis** [Yixin-Hu/TetWild#9]
Can anyone confirm building successfully on this platform?
Thanks

<img width="1676" alt="screen shot 2018-06-16 at 13 59 52" src="https://user-images.githubusercontent.com/658719/41498453-a218d4d8-716e-11e8-893b-9544d2f7114b.png">

**Comment by nyotis** [comment]
Hmm... my $PATH includes the homebrew I use for CGAL and Boost -- apparently, this is not enough. Can anyone confirm building the source on OS X? I do not want to edit CMakeLists.txt unless if there is no alternative

Cheers!

**Comment by nyotis** [comment]
**MacOSX10.13.sdk**

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk

**Comment by Yixin-Hu** [comment]
Hi,

The code was originally developed on MacOS and it can be compiled on both of my two mac machines.

I'm also using MacOSX10.13.sdk. 

I don't know which IDE are you using. Did you try using command line directly?

**Comment by nyotis** [comment]
Thanks @Yixin-Hu 
It turns out that re-installing a fresh CGAL version and setting the CGAL_DIR fixes the issue -- your CmakeLists is simple and seems OK.

**Comment by nyotis** [comment]
so, its all good, feel free to close this

**Comment by Yixin-Hu** [comment]
Cool.
