### ISSUE TITLE
is this repo maintained

### ISSUE THREAD

**Issue by XuliaDS** [Yixin-Hu/TetWild#93]
Hi, 
I left a comment here https://github.com/wildmeshing/fTetWild/issues/62#issue-1872023967
but I am not sure if that is the official repo or this one is.

Many many thanks!

**Comment by Yixin-Hu** [comment]
Hi,

Both TetWild and fTetWild are official repo. I've replied your original question on fTetWild repo.

**Comment by XuliaDS** [comment]
Thanks, I replied in the other post.
